import React from 'react'
import { Grid, Button, TextField } from '@material-ui/core'
import styles from '../styles/admin.module.scss'
import Head from 'next/head'

const Admin = () => {
    return (
        <>
            <Head>
                <title>Drona | Admin Login</title>
                <link rel="manifest" href="/manifest.json" />
                <link rel="apple-touch-icon" href="/256x256.png"></link>
                <meta name="theme-color" content="#fff" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/256x256.png" />
            </Head>
            <div className={styles.container}>
                <Grid container className={styles.card}>
                    <Grid item xs={12} sm={12} md={7}>
                        <img
                            src="https://res.cloudinary.com/dguy8qpzi/image/upload/v1635971918/login-drona_ae2rap.png"
                            style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                        />
                    </Grid>
                    <Grid container item xs={12} sm={12} md={5} alignItems="center" direction="column" style={{ padding: 10 }}>
                        <div className={styles.form}>
                            <div className={styles.name}>DRONA</div>

                            <div className={styles.heading}>Log in to your account</div>

                            <TextField
                                id="outlined-basic"
                                variant="outlined"
                                label="Email address"
                                margin="normal"
                                type="email"
                                className={styles.formText}
                                // onChange={e => setTitle(e.target.value)}
                            />

                            <TextField
                                id="outlined-basic"
                                variant="outlined"
                                label="Password"
                                margin="normal"
                                type="password"
                                className={styles.formText}
                                // onChange={e => setTitle(e.target.value)}
                            />
                            <br />
                            <Button style={{ backgroundColor: '#000', color: '#FFFFFF', fontWeight: 800 }}>Log In</Button>
                        </div>
                    </Grid>
                </Grid>
            </div>
        </>
    )
}

export default Admin
