import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'

function Contribute() {
    const [questions, setQuestions] = useState<any[]>([])

    useEffect(() => {
        if (localStorage.getItem('token')) {
            let teamName = 'Betaoverflow'
        } else {
            alert("You're not logged in.")
            window.location.href = '/admin'
        }
    })
    return (
        <>
            <Head>
                <title>Drona | Dashboard</title>
                <link rel="manifest" href="/manifest.json" />
                <link rel="apple-touch-icon" href="/256x256.png"></link>
                <meta name="theme-color" content="#fff" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/256x256.png" />
            </Head>
            <div>
                <img src="https://res.cloudinary.com/dguy8qpzi/image/upload/v1636649699/profile_yn5nhh.png" alt="Profile picture" className="profile_img"/>
                <h1>Hey Admin 👋 </h1>
                <div>
                    <Link href="/dashboard/questionVerify">Verify Question!</Link>
                </div>
                <div>
                    <Link href="/dashboard/opportunityVerify">Verify Opportunity!</Link>
                </div>
            </div>
        </>
    )
}

export default Contribute
